// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUCtjg-5opD8QgNH-GcpioOWD_vQfstyw',
    appId: '1:256034812149:web:83597678049ccaf37355bc',
    messagingSenderId: '256034812149',
    projectId: 'pushexamplechouchou',
    authDomain: 'pushexamplechouchou.firebaseapp.com',
    storageBucket: 'pushexamplechouchou.appspot.com',
    measurementId: 'G-BNYY8NNPPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwGdU_U0Pl3HckXHdAIGldInArz90BuKU',
    appId: '1:256034812149:android:3d265f34b72062ee7355bc',
    messagingSenderId: '256034812149',
    projectId: 'pushexamplechouchou',
    storageBucket: 'pushexamplechouchou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQGvD54ZqDJNLK1lObQOKLpZny9mNjHBw',
    appId: '1:256034812149:ios:8fc261c95d66f2ad7355bc',
    messagingSenderId: '256034812149',
    projectId: 'pushexamplechouchou',
    storageBucket: 'pushexamplechouchou.appspot.com',
    iosBundleId: 'com.example.pushExampleChouChou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQGvD54ZqDJNLK1lObQOKLpZny9mNjHBw',
    appId: '1:256034812149:ios:fdbcc3bda6e5187f7355bc',
    messagingSenderId: '256034812149',
    projectId: 'pushexamplechouchou',
    storageBucket: 'pushexamplechouchou.appspot.com',
    iosBundleId: 'com.example.pushExample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUCtjg-5opD8QgNH-GcpioOWD_vQfstyw',
    appId: '1:256034812149:web:b870a868822d81317355bc',
    messagingSenderId: '256034812149',
    projectId: 'pushexamplechouchou',
    authDomain: 'pushexamplechouchou.firebaseapp.com',
    storageBucket: 'pushexamplechouchou.appspot.com',
    measurementId: 'G-0QGWG4XCZ0',
  );
}
